### ISSUE TITLE
Products in mal pop up missing

### ISSUE THREAD

**Issue by leoMehlig** [WVV-Crowd-Sourced-Stock-Tracking/ios-app#5]

**Comment by leoMehlig** [comment]
what did I mean by that?

**Comment by Veeit** [comment]
Ich glaube du meintest das Produkte in map pop up nicht angezeigt werden. Ich denke wir müssten das einfach zweizeilig machen

**Comment by leoMehlig** [comment]
Stimmt. Ja das sollt eigentlich schon gehen. Hatte das ja schon implementiert
